export type QuestionCategory = 'opener' | 'deepdive' | 'integration' | 'era' | 'music_induced' | 'video_induced'
export type LifeStage = 'childhood' | 'school' | 'youth' | 'family' | 'prime' | 'senior' | 'present'
export type DifficultyLevel = 1 | 2 | 3

export interface Question {
  id: string
  category: QuestionCategory
  lifeStage: LifeStage
  difficulty: DifficultyLevel
  text: string
  followups?: string[]
}

export const questions: Question[] = [
  // ── 幼少期 childhood ───────────────────────────────────────────────
  { id: 'op_childhood_001', category: 'opener', lifeStage: 'childhood', difficulty: 1,
    text: '子どものころ、どんな遊びが好きでしたか？',
    followups: ['誰と一緒に遊んでいましたか？', 'どこで遊んでいましたか？'] },
  { id: 'op_childhood_002', category: 'opener', lifeStage: 'childhood', difficulty: 1,
    text: '子どものころ、家の近くにはどんな景色がありましたか？',
    followups: ['田んぼや畑はありましたか？', '川や山はありましたか？'] },
  { id: 'op_childhood_003', category: 'opener', lifeStage: 'childhood', difficulty: 1,
    text: '小さいころ、一番好きだった食べ物は何ですか？',
    followups: ['お母さんが作ってくれましたか？', '今でも食べますか？'] },
  { id: 'op_childhood_004', category: 'opener', lifeStage: 'childhood', difficulty: 1,
    text: 'お正月はどんなふうに過ごしていましたか？',
    followups: ['お年玉はもらいましたか？', '親戚が集まりましたか？'] },
  { id: 'op_childhood_005', category: 'opener', lifeStage: 'childhood', difficulty: 1,
    text: '子どものころ、家にはどんな動物がいましたか？',
    followups: ['犬や猫を飼っていましたか？', 'どんな名前でしたか？'] },
  { id: 'dd_childhood_001', category: 'deepdive', lifeStage: 'childhood', difficulty: 2,
    text: '子どものころ、よく遊んだ友だちを覚えていますか？',
    followups: ['その子とはどんな遊びをしましたか？', '今も連絡は取っていますか？'] },
  { id: 'dd_childhood_002', category: 'deepdive', lifeStage: 'childhood', difficulty: 2,
    text: '子どものころ、どんな夢を持っていましたか？',
    followups: ['その夢は叶いましたか？', '誰かに話したことがありますか？'] },
  { id: 'dd_childhood_003', category: 'deepdive', lifeStage: 'childhood', difficulty: 2,
    text: 'お父さん・お母さんはどんな人でしたか？',
    followups: ['厳しい方でしたか？', '一番思い出に残ることは何ですか？'] },
  { id: 'dd_childhood_004', category: 'deepdive', lifeStage: 'childhood', difficulty: 2,
    text: '兄弟や姉妹はいましたか？どんな関係でしたか？',
    followups: ['よくケンカしましたか？', '仲良しでしたか？'] },
  { id: 'dd_childhood_005', category: 'deepdive', lifeStage: 'childhood', difficulty: 3,
    text: '子どものころ、家の中でのルールや決まりごとはありましたか？',
    followups: ['食事の時間は決まっていましたか？', '門限はありましたか？'] },
  { id: 'era_childhood_001', category: 'era', lifeStage: 'childhood', difficulty: 2,
    text: '子どものころ、テレビや映画で好きだったものはありましたか？',
    followups: ['どんな番組が好きでしたか？', 'ラジオも聴いていましたか？'] },
  { id: 'era_childhood_002', category: 'era', lifeStage: 'childhood', difficulty: 2,
    text: '子どものころのお菓子や駄菓子で、思い出のものはありますか？',
    followups: ['どこで買っていましたか？', '何円くらいしましたか？'] },
  { id: 'music_childhood_001', category: 'music_induced', lifeStage: 'childhood', difficulty: 1,
    text: 'この曲を聴くと、子どものころのどんな場面を思い出しますか？',
    followups: ['誰と一緒でしたか？', 'どんな気持ちになりますか？'] },
  { id: 'music_childhood_002', category: 'music_induced', lifeStage: 'childhood', difficulty: 1,
    text: '子どものころ、歌っていた歌はありますか？',
    followups: ['学校で習いましたか？', '家族で歌いましたか？'] },
  { id: 'video_childhood_001', category: 'video_induced', lifeStage: 'childhood', difficulty: 1,
    text: 'この映像で、懐かしいものはありましたか？',
    followups: ['どんなことを思い出しましたか？'] },
  { id: 'video_childhood_002', category: 'video_induced', lifeStage: 'childhood', difficulty: 1,
    text: '昔の街並みや景色を見て、何か感じることはありますか？',
    followups: ['住んでいた場所に似ていますか？'] },

  // ── 学校時代 school ────────────────────────────────────────────────
  { id: 'op_school_001', category: 'opener', lifeStage: 'school', difficulty: 1,
    text: '学校で一番好きだった先生を教えてください。',
    followups: ['どんな先生でしたか？', 'その先生に言われて印象に残っていることはありますか？'] },
  { id: 'op_school_002', category: 'opener', lifeStage: 'school', difficulty: 1,
    text: '学校で好きだった教科は何ですか？',
    followups: ['なぜ好きでしたか？', '得意でしたか？'] },
  { id: 'op_school_003', category: 'opener', lifeStage: 'school', difficulty: 1,
    text: '学校の給食で好きなメニューはありましたか？',
    followups: ['今でも食べたいと思いますか？'] },
  { id: 'op_school_004', category: 'opener', lifeStage: 'school', difficulty: 1,
    text: '学生時代に入っていた部活や習い事はありましたか？',
    followups: ['何年くらい続けましたか？', '試合や発表会はありましたか？'] },
  { id: 'op_school_005', category: 'opener', lifeStage: 'school', difficulty: 1,
    text: '修学旅行はどこに行きましたか？',
    followups: ['一番の思い出は何ですか？', '誰と同じ部屋でしたか？'] },
  { id: 'dd_school_001', category: 'deepdive', lifeStage: 'school', difficulty: 2,
    text: '学生時代の親友を教えてください。',
    followups: ['どこで知り合いましたか？', '今も連絡を取っていますか？'] },
  { id: 'dd_school_002', category: 'deepdive', lifeStage: 'school', difficulty: 2,
    text: '学校でいたずらや悪さをしたことはありますか？',
    followups: ['先生に怒られましたか？', '笑って話せる思い出ですか？'] },
  { id: 'dd_school_003', category: 'deepdive', lifeStage: 'school', difficulty: 2,
    text: '卒業式のとき、どんな気持ちでしたか？',
    followups: ['泣きましたか？', '誰と一緒にいましたか？'] },
  { id: 'dd_school_004', category: 'deepdive', lifeStage: 'school', difficulty: 3,
    text: '学生時代に頑張ったことで、今でも誇りに思うことはありますか？',
    followups: ['それはどんな経験でしたか？', '周りに評価されましたか？'] },
  { id: 'era_school_001', category: 'era', lifeStage: 'school', difficulty: 2,
    text: '学生時代に流行っていたものや遊びはありましたか？',
    followups: ['みんなで夢中になったものはありますか？'] },
  { id: 'music_school_001', category: 'music_induced', lifeStage: 'school', difficulty: 1,
    text: 'この曲を聴いて、学生時代のことが浮かんできましたか？',
    followups: ['どんな場面ですか？', '誰かの顔が浮かびますか？'] },
  { id: 'video_school_001', category: 'video_induced', lifeStage: 'school', difficulty: 1,
    text: 'この映像を見て、学校での出来事を思い出しましたか？',
    followups: ['楽しかった思い出はありますか？'] },

  // ── 青年期 youth ───────────────────────────────────────────────────
  { id: 'op_youth_001', category: 'opener', lifeStage: 'youth', difficulty: 1,
    text: '初めて就職したとき、どんなお仕事でしたか？',
    followups: ['職場はどんな雰囲気でしたか？', '上司はどんな方でしたか？'] },
  { id: 'op_youth_002', category: 'opener', lifeStage: 'youth', difficulty: 1,
    text: '若いころに夢中になっていた趣味はありましたか？',
    followups: ['今でも続けていますか？', '誰かと一緒にやっていましたか？'] },
  { id: 'op_youth_003', category: 'opener', lifeStage: 'youth', difficulty: 1,
    text: '若いころによく行っていた場所はありますか？',
    followups: ['どんな場所でしたか？', '今はまだありますか？'] },
  { id: 'op_youth_004', category: 'opener', lifeStage: 'youth', difficulty: 1,
    text: '若いころ、どんな服が好きでしたか？',
    followups: ['流行の服を着ていましたか？', 'どこで買っていましたか？'] },
  { id: 'op_youth_005', category: 'opener', lifeStage: 'youth', difficulty: 1,
    text: '若いころに食べた、おいしかった料理を教えてください。',
    followups: ['どこで食べましたか？', '誰と一緒でしたか？'] },
  { id: 'dd_youth_001', category: 'deepdive', lifeStage: 'youth', difficulty: 2,
    text: '初めてお給料をもらったとき、どんな気持ちでしたか？',
    followups: ['そのお金で何をしましたか？', '誰かに報告しましたか？'] },
  { id: 'dd_youth_002', category: 'deepdive', lifeStage: 'youth', difficulty: 2,
    text: '初めて一人暮らしをしたときのことを教えてください。',
    followups: ['どんな場所に住んでいましたか？', '寂しくなかったですか？'] },
  { id: 'dd_youth_003', category: 'deepdive', lifeStage: 'youth', difficulty: 2,
    text: '若いころに一番感動した出来事は何ですか？',
    followups: ['その時のことを詳しく教えてください。'] },
  { id: 'dd_youth_004', category: 'deepdive', lifeStage: 'youth', difficulty: 2,
    text: '若いころ、尊敬していた人はいましたか？',
    followups: ['どんな点を尊敬していましたか？', '会ったことはありますか？'] },
  { id: 'dd_youth_005', category: 'deepdive', lifeStage: 'youth', difficulty: 3,
    text: '人生の転機になった出来事は何ですか？',
    followups: ['その出来事は今の自分にどう影響しましたか？'] },
  { id: 'era_youth_001', category: 'era', lifeStage: 'youth', difficulty: 2,
    text: '若いころ、どんな音楽が流行っていましたか？',
    followups: ['好きな歌手や曲はありましたか？'] },
  { id: 'era_youth_002', category: 'era', lifeStage: 'youth', difficulty: 2,
    text: '若いころのテレビ番組で印象に残っているものはありますか？',
    followups: ['よく見ていた番組はどれですか？'] },
  { id: 'music_youth_001', category: 'music_induced', lifeStage: 'youth', difficulty: 1,
    text: 'この曲を聴くと、どんな場面を思い出しますか？',
    followups: ['誰といましたか？', 'どんな気持ちになりますか？'] },
  { id: 'music_youth_002', category: 'music_induced', lifeStage: 'youth', difficulty: 2,
    text: '若いころよく聴いていた曲はありますか？',
    followups: ['どこで聴いていましたか？', '誰かと一緒に聴きましたか？'] },
  { id: 'video_youth_001', category: 'video_induced', lifeStage: 'youth', difficulty: 1,
    text: 'この映像を見て、若いころのことが思い出されましたか？',
    followups: ['どんな気持ちになりましたか？'] },

  // ── 家庭期 family ──────────────────────────────────────────────────
  { id: 'op_family_001', category: 'opener', lifeStage: 'family', difficulty: 1,
    text: 'ご結婚のときのことを教えてください。',
    followups: ['どんな式でしたか？', 'どこで出会いましたか？'] },
  { id: 'op_family_002', category: 'opener', lifeStage: 'family', difficulty: 1,
    text: 'お子さんが生まれたときのことを教えてください。',
    followups: ['どんな名前にしましたか？', 'どんな気持ちでしたか？'] },
  { id: 'op_family_003', category: 'opener', lifeStage: 'family', difficulty: 1,
    text: '家族みんなで出かけた旅行で思い出のものはありますか？',
    followups: ['どこに行きましたか？', '子どもたちは喜んでいましたか？'] },
  { id: 'op_family_004', category: 'opener', lifeStage: 'family', difficulty: 1,
    text: '家族の誕生日や記念日はどんなふうに祝っていましたか？',
    followups: ['ケーキは買いましたか？', '子どもたちは何を喜びましたか？'] },
  { id: 'op_family_005', category: 'opener', lifeStage: 'family', difficulty: 1,
    text: '子育てで一番大変だったことは何ですか？',
    followups: ['誰かに助けてもらいましたか？', '今では笑い話になっていますか？'] },
  { id: 'dd_family_001', category: 'deepdive', lifeStage: 'family', difficulty: 2,
    text: 'お子さんへの一番の思い出を教えてください。',
    followups: ['そのときお子さんは何歳でしたか？', '今でも話しますか？'] },
  { id: 'dd_family_002', category: 'deepdive', lifeStage: 'family', difficulty: 2,
    text: 'パートナーと喧嘩して、仲直りしたときのことを教えてください。',
    followups: ['どんなことが原因でしたか？', '仲直りの方法はどんなものでしたか？'] },
  { id: 'dd_family_003', category: 'deepdive', lifeStage: 'family', difficulty: 2,
    text: '子どもたちを育てるうえで、一番大切にしてきたことは何ですか？',
    followups: ['それはどこから学びましたか？', '子どもたちに伝わっていると思いますか？'] },
  { id: 'dd_family_004', category: 'deepdive', lifeStage: 'family', difficulty: 3,
    text: '家族みんなで一緒に食べた食事で、一番思い出深いものはどんな料理ですか？',
    followups: ['誰が作りましたか？', 'その料理のレシピはありますか？'] },
  { id: 'era_family_001', category: 'era', lifeStage: 'family', difficulty: 2,
    text: '子育て中の時代に流行していたもので、印象に残っているものはありますか？',
    followups: ['子どもたちも影響を受けましたか？'] },
  { id: 'music_family_001', category: 'music_induced', lifeStage: 'family', difficulty: 1,
    text: 'この曲を聴いて、家族と過ごした場面が浮かびましたか？',
    followups: ['どんな場面ですか？', '誰のことが浮かびましたか？'] },
  { id: 'video_family_001', category: 'video_induced', lifeStage: 'family', difficulty: 1,
    text: 'この映像を見て、家族のことを思い出しましたか？',
    followups: ['どんな気持ちになりましたか？'] },

  // ── 働き盛り prime ─────────────────────────────────────────────────
  { id: 'op_prime_001', category: 'opener', lifeStage: 'prime', difficulty: 1,
    text: 'お仕事で一番やりがいを感じたことは何ですか？',
    followups: ['どんな仕事でしたか？', '周りからはどう言われましたか？'] },
  { id: 'op_prime_002', category: 'opener', lifeStage: 'prime', difficulty: 1,
    text: 'お仕事で一番誇りに思う成果は何ですか？',
    followups: ['何年くらいかかりましたか？', '誰かに認めてもらえましたか？'] },
  { id: 'op_prime_003', category: 'opener', lifeStage: 'prime', difficulty: 1,
    text: '職場の仲間で、今でも印象に残っている方はいますか？',
    followups: ['どんな方でしたか？', '今も連絡は取っていますか？'] },
  { id: 'op_prime_004', category: 'opener', lifeStage: 'prime', difficulty: 1,
    text: 'お仕事で一番つらかったことは何ですか？',
    followups: ['それをどうやって乗り越えましたか？', '誰かに相談しましたか？'] },
  { id: 'op_prime_005', category: 'opener', lifeStage: 'prime', difficulty: 1,
    text: '働きながら趣味や余暇を楽しんでいましたか？',
    followups: ['どんな趣味でしたか？', '誰と楽しんでいましたか？'] },
  { id: 'dd_prime_001', category: 'deepdive', lifeStage: 'prime', difficulty: 2,
    text: '仕事でピンチのときに、助けてくれた人はいますか？',
    followups: ['どんな状況でしたか？', '今でも感謝していますか？'] },
  { id: 'dd_prime_002', category: 'deepdive', lifeStage: 'prime', difficulty: 2,
    text: '後輩や部下に伝えてきたことで、一番大切なことは何ですか？',
    followups: ['それはどこで学びましたか？', '受け継いでくれた人はいますか？'] },
  { id: 'dd_prime_003', category: 'deepdive', lifeStage: 'prime', difficulty: 3,
    text: '仕事と家庭のバランスをどうやってとっていましたか？',
    followups: ['難しかったですか？', '家族に感謝していることはありますか？'] },
  { id: 'music_prime_001', category: 'music_induced', lifeStage: 'prime', difficulty: 1,
    text: 'この曲を聴いて、仕事をしていたころのことが思い出されましたか？',
    followups: ['どんな時代の曲ですか？', '職場でもよく聴いていましたか？'] },
  { id: 'video_prime_001', category: 'video_induced', lifeStage: 'prime', difficulty: 1,
    text: 'この映像を見て、働き盛りのころのことを思い出しましたか？',
    followups: ['当時と今では何が変わったと思いますか？'] },

  // ── 晩年期 senior ──────────────────────────────────────────────────
  { id: 'op_senior_001', category: 'opener', lifeStage: 'senior', difficulty: 1,
    text: '定年後はどんな生活をされていましたか？',
    followups: ['楽しみにしていたことはありましたか？', '毎日の日課はありましたか？'] },
  { id: 'op_senior_002', category: 'opener', lifeStage: 'senior', difficulty: 1,
    text: '定年後に始めた趣味やことはありますか？',
    followups: ['誰かに教えてもらいましたか？', '今でも続けていますか？'] },
  { id: 'op_senior_003', category: 'opener', lifeStage: 'senior', difficulty: 1,
    text: '老後の旅行で印象に残っているものはありますか？',
    followups: ['誰と行きましたか？', '一番よかった場所はどこですか？'] },
  { id: 'op_senior_004', category: 'opener', lifeStage: 'senior', difficulty: 1,
    text: '孫やひ孫との思い出で一番心に残っているものを教えてください。',
    followups: ['何歳のころのことですか？', '今でも会いますか？'] },
  { id: 'dd_senior_001', category: 'deepdive', lifeStage: 'senior', difficulty: 2,
    text: '年を重ねて、若いころと比べて変わったと感じることはありますか？',
    followups: ['よくなったと感じることはありますか？', '大切にするものが変わりましたか？'] },
  { id: 'dd_senior_002', category: 'deepdive', lifeStage: 'senior', difficulty: 2,
    text: 'これまでの人生を振り返って、一番の宝は何ですか？',
    followups: ['それはいつ気づきましたか？'] },
  { id: 'music_senior_001', category: 'music_induced', lifeStage: 'senior', difficulty: 1,
    text: 'この曲を聴いて、ゆったりとした気持ちになりましたか？',
    followups: ['心地よい音楽ですか？', '昔からよく聴いていた曲ですか？'] },
  { id: 'video_senior_001', category: 'video_induced', lifeStage: 'senior', difficulty: 1,
    text: 'この映像を見て、気持ちはいかがですか？',
    followups: ['懐かしい感じがしますか？'] },

  // ── 現在 present ───────────────────────────────────────────────────
  { id: 'op_present_001', category: 'opener', lifeStage: 'present', difficulty: 1,
    text: '最近、嬉しかったことや楽しかったことを教えてください。',
    followups: ['誰と一緒でしたか？', 'またやってみたいですか？'] },
  { id: 'op_present_002', category: 'opener', lifeStage: 'present', difficulty: 1,
    text: '今、楽しみにしていることはありますか？',
    followups: ['いつ頃ですか？', '誰かと一緒ですか？'] },
  { id: 'op_present_003', category: 'opener', lifeStage: 'present', difficulty: 1,
    text: '今の生活で一番好きな時間はいつですか？',
    followups: ['どんなことをしていますか？', '毎日ありますか？'] },
  { id: 'int_present_001', category: 'integration', lifeStage: 'present', difficulty: 2,
    text: 'あなたの人生で、一番誇りに思うことは何ですか？',
    followups: [] },
  { id: 'int_present_002', category: 'integration', lifeStage: 'present', difficulty: 2,
    text: 'これまでの人生で、一番ありがとうと言いたい人は誰ですか？',
    followups: ['その方に伝えたことはありますか？', 'どんなことをしてもらいましたか？'] },
  { id: 'int_present_003', category: 'integration', lifeStage: 'present', difficulty: 2,
    text: '若い人に伝えたい、人生の知恵はありますか？',
    followups: ['それはどんな経験から学びましたか？'] },
  { id: 'int_present_004', category: 'integration', lifeStage: 'present', difficulty: 3,
    text: 'もし人生をもう一度やり直せるとしたら、やり直したいことはありますか？',
    followups: ['それはなぜですか？'] },
  { id: 'int_present_005', category: 'integration', lifeStage: 'present', difficulty: 2,
    text: '自分の人生を一言で表すとしたら、どんな言葉になりますか？',
    followups: ['なぜその言葉を選びましたか？'] },
  { id: 'music_present_001', category: 'music_induced', lifeStage: 'present', difficulty: 1,
    text: 'この曲を聴いて、今どんな気持ちになりましたか？',
    followups: ['好きな曲ですか？', '誰かを思い出しますか？'] },
  { id: 'video_present_001', category: 'video_induced', lifeStage: 'present', difficulty: 1,
    text: 'この映像を見て、どんなことを感じましたか？',
    followups: ['何か話したいことがありますか？'] },

  // ── 追加：幼少期 childhood（深掘り・時代）─────────────────────────
  { id: 'dd_childhood_006', category: 'deepdive', lifeStage: 'childhood', difficulty: 2,
    text: '子どものころ、一番怖かった体験は何ですか？',
    followups: ['誰かに助けてもらいましたか？', '今では笑い話ですか？'] },
  { id: 'dd_childhood_007', category: 'deepdive', lifeStage: 'childhood', difficulty: 1,
    text: '七夕やお盆など、季節の行事はどんなふうに過ごしていましたか？',
    followups: ['家族みんなでやりましたか？', '近所の人も集まりましたか？'] },
  { id: 'era_childhood_003', category: 'era', lifeStage: 'childhood', difficulty: 2,
    text: '子どものころ、近所の商店街やお店で印象に残っているところはありますか？',
    followups: ['よく買い物に行きましたか？', '今もそのお店はありますか？'] },
  { id: 'dd_childhood_008', category: 'deepdive', lifeStage: 'childhood', difficulty: 2,
    text: '子どものころ、病気やケガをしたときのことを覚えていますか？',
    followups: ['誰が看病してくれましたか？', '大変でしたか？'] },
  { id: 'op_childhood_006', category: 'opener', lifeStage: 'childhood', difficulty: 1,
    text: '子どものころ、どんな乗り物が好きでしたか？',
    followups: ['電車や汽車に乗ったことはありますか？', '初めて乗ったときのことを覚えていますか？'] },

  // ── 追加：学校時代 school（深掘り）────────────────────────────────
  { id: 'dd_school_005', category: 'deepdive', lifeStage: 'school', difficulty: 2,
    text: '学芸会や文化祭などの行事で印象に残っていることはありますか？',
    followups: ['どんな役でしたか？', '緊張しましたか？'] },
  { id: 'dd_school_006', category: 'deepdive', lifeStage: 'school', difficulty: 2,
    text: '学生時代に夢中になって読んだ本はありますか？',
    followups: ['どんな内容でしたか？', '今でも覚えていますか？'] },
  { id: 'op_school_006', category: 'opener', lifeStage: 'school', difficulty: 1,
    text: '運動会で一番思い出に残っている種目は何ですか？',
    followups: ['活躍できましたか？', '家族は見に来ましたか？'] },
  { id: 'era_school_002', category: 'era', lifeStage: 'school', difficulty: 2,
    text: '学生のころ使っていた文房具や道具で、今も覚えているものはありますか？',
    followups: ['大切に使っていましたか？'] },
  { id: 'dd_school_007', category: 'deepdive', lifeStage: 'school', difficulty: 3,
    text: '進学や就職を決めるとき、誰かに相談しましたか？',
    followups: ['その助言は役に立ちましたか？', '今でもその方に感謝していますか？'] },

  // ── 追加：青年期 youth（深掘り）───────────────────────────────────
  { id: 'dd_youth_006', category: 'deepdive', lifeStage: 'youth', difficulty: 2,
    text: '若いころに旅した場所で、一番印象に残っているところはどこですか？',
    followups: ['誰と行きましたか？', 'また行きたいですか？'] },
  { id: 'op_youth_006', category: 'opener', lifeStage: 'youth', difficulty: 1,
    text: '若いころに乗っていた車やバイクはありますか？',
    followups: ['どんな車でしたか？', '思い出はありますか？'] },
  { id: 'dd_youth_007', category: 'deepdive', lifeStage: 'youth', difficulty: 2,
    text: '初めて恋をしたときのことを教えてください（差し支えなければ）。',
    followups: ['どんな方でしたか？', 'ドキドキしましたか？'] },
  { id: 'era_youth_003', category: 'era', lifeStage: 'youth', difficulty: 2,
    text: '若いころよく通っていたお気に入りのお店やレストランはありますか？',
    followups: ['何を食べていましたか？', '今もそのお店はありますか？'] },
  { id: 'dd_youth_008', category: 'deepdive', lifeStage: 'youth', difficulty: 2,
    text: '若いころ、一番お世話になった人は誰ですか？',
    followups: ['どんなことを教えてもらいましたか？', '今も連絡は取っていますか？'] },

  // ── 追加：家庭期 family（深掘り）──────────────────────────────────
  { id: 'dd_family_005', category: 'deepdive', lifeStage: 'family', difficulty: 2,
    text: '家族でよく作っていた料理や食卓の思い出を教えてください。',
    followups: ['誰がよく作っていましたか？', '子どもたちは好きでしたか？'] },
  { id: 'dd_family_006', category: 'deepdive', lifeStage: 'family', difficulty: 2,
    text: '子どもたちを育てて、一番嬉しかった瞬間はいつですか？',
    followups: ['何歳のころですか？', 'そのときの子どもの顔が浮かびますか？'] },
  { id: 'op_family_006', category: 'opener', lifeStage: 'family', difficulty: 1,
    text: '家族でよく見ていたテレビ番組はありますか？',
    followups: ['毎週楽しみにしていましたか？', 'みんなで一緒に見ていましたか？'] },
  { id: 'era_family_002', category: 'era', lifeStage: 'family', difficulty: 2,
    text: '子育て中の時代の出来事で、今でも印象に残っているニュースはありますか？',
    followups: ['そのとき家族はどんな反応でしたか？'] },
  { id: 'dd_family_007', category: 'deepdive', lifeStage: 'family', difficulty: 2,
    text: '子どもたちを学校に送り出す朝のことを覚えていますか？',
    followups: ['どんな朝ご飯を食べていましたか？', '声をかけていた言葉はありますか？'] },

  // ── 追加：働き盛り prime（深掘り）────────────────────────────────
  { id: 'dd_prime_004', category: 'deepdive', lifeStage: 'prime', difficulty: 2,
    text: '仕事で海外に行ったことはありますか？',
    followups: ['どこの国でしたか？', 'びっくりしたことはありますか？'] },
  { id: 'dd_prime_005', category: 'deepdive', lifeStage: 'prime', difficulty: 2,
    text: '仕事で一番長く取り組んだプロジェクトや仕事はどんなものでしたか？',
    followups: ['何年かかりましたか？', '達成感はありましたか？'] },
  { id: 'op_prime_006', category: 'opener', lifeStage: 'prime', difficulty: 1,
    text: '仕事帰りによく立ち寄っていたお店や場所はありますか？',
    followups: ['仲間と一緒でしたか？', 'どんな時間でしたか？'] },
  { id: 'dd_prime_006', category: 'deepdive', lifeStage: 'prime', difficulty: 3,
    text: '仕事を通じて、一番学んだことは何ですか？',
    followups: ['今の生活でも役立っていますか？'] },
  { id: 'era_prime_001', category: 'era', lifeStage: 'prime', difficulty: 2,
    text: '働き盛りのころ、社会や世の中で大きな出来事はありましたか？',
    followups: ['仕事に影響はありましたか？', '家族との話題になりましたか？'] },

  // ── 追加：晩年期 senior（深掘り）────────────────────────────────
  { id: 'dd_senior_003', category: 'deepdive', lifeStage: 'senior', difficulty: 2,
    text: '定年後、地域の活動やボランティアに参加したことはありますか？',
    followups: ['どんな活動でしたか？', '仲間はできましたか？'] },
  { id: 'dd_senior_004', category: 'deepdive', lifeStage: 'senior', difficulty: 2,
    text: 'シニアになってから、新しく挑戦したことはありますか？',
    followups: ['どんなことでしたか？', '楽しめましたか？'] },
  { id: 'op_senior_005', category: 'opener', lifeStage: 'senior', difficulty: 1,
    text: '季節の行事（花見・紅葉・年末年始など）で、楽しみにしているものはありますか？',
    followups: ['誰と一緒ですか？', '毎年恒例ですか？'] },
  { id: 'dd_senior_005', category: 'deepdive', lifeStage: 'senior', difficulty: 2,
    text: '自分の健康管理で、気をつけていることはありますか？',
    followups: ['誰かに言われて始めましたか？'] },
  { id: 'int_senior_001', category: 'integration', lifeStage: 'senior', difficulty: 2,
    text: '人生を豊かにしてくれたものは何だと思いますか？',
    followups: ['それはいつ気づきましたか？', '若い人にも伝えたいですか？'] },

  // ── 追加：現在 present（統合・まとめ）────────────────────────────
  { id: 'int_present_006', category: 'integration', lifeStage: 'present', difficulty: 2,
    text: '今の自分を支えてくれている人や物はありますか？',
    followups: ['それはどんな存在ですか？', '感謝は伝えていますか？'] },
  { id: 'int_present_007', category: 'integration', lifeStage: 'present', difficulty: 1,
    text: '毎日の生活で「これだけは欠かせない」というものはありますか？',
    followups: ['いつからそうなりましたか？'] },
  { id: 'int_present_008', category: 'integration', lifeStage: 'present', difficulty: 2,
    text: '大切な人に伝えたいことはありますか？',
    followups: ['直接伝えたことはありますか？'] },
  { id: 'op_present_004', category: 'opener', lifeStage: 'present', difficulty: 1,
    text: '最近、おいしかった食べ物を教えてください。',
    followups: ['誰と食べましたか？', 'また食べたいですか？'] },
  { id: 'op_present_005', category: 'opener', lifeStage: 'present', difficulty: 1,
    text: '最近見た景色やものの中で、きれいだと思ったものはありますか？',
    followups: ['どこで見ましたか？', '写真は撮りましたか？'] },
]
